version: 2.1
jobs:
  frontend:
    docker:
      - image: cimg/node:20.11
    steps:
      - checkout
      - restore_cache:
          key: catnip-npm-dependencies-{{ checksum "frontend/package.json" }}
      - run:
          name: Installing dependencies
          working_directory: ./frontend
          command: npm ci
      - save_cache:
          key: catnip-npm-dependencies-{{ checksum "frontend/package.json" }}
          paths:
            - ./frontend/node_modules
      - run:
          name: Building the frontend
          working_directory: ./frontend
          command: npm run build
      - save_cache:
          key: catnip-frontend-{{ or .Environment.CIRCLE_TAG .Environment.CIRCLE_SHA1 }}
          paths:
            - ./frontend/dist/

  backend:
    docker:
      - image: docker.subshell.com/builder/golang-builder:1.4.0
        auth:
          username: $DOCKER_USERNAME
          password: $DOCKER_PASSWORD
    steps:
      - checkout
      - restore_cache:
          keys:
            - oneko-catnip-go-mod-{{ checksum "go.sum" }}
      - run:
          name: Install dependencies
          command: go mod download
      - save_cache:
          key: oneko-catnip-go-mod-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"
      - run:
          name: Run tests
          command: make go-test-ci
      - store_test_results:
          path: ./test_results.xml
      - run:
          name: Lint
          command: make go-lint-ci
      - store_test_results:
          path: ./linter_results.xml
      - run:
          name: Build the application
          command: make go-build-for-docker
      - run: mkdir ./circle-artifacts && cp ./o-neko-catnip ./circle-artifacts/
      - save_cache:
          key: oneko-catnip-artifacts-{{ or .Environment.CIRCLE_TAG .Environment.CIRCLE_SHA1 }}
          paths:
            - ./circle-artifacts/
      - store_artifacts:
          path: ./circle-artifacts/

  dockerize_dev:
    docker:
      - image: docker:19
    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          key: oneko-catnip-artifacts-{{ or .Environment.CIRCLE_TAG .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          key: catnip-frontend-{{ or .Environment.CIRCLE_TAG .Environment.CIRCLE_SHA1 }}
      - run: mv /home/circleci/project/frontend/dist ./frontend/dist
      - run: cp ./circle-artifacts/o-neko-catnip .
      - run: docker build -t subshellgmbh/o-neko-catnip:latest-dev .
      - run: echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
      - run: docker push subshellgmbh/o-neko-catnip:latest-dev

  release:
    docker:
      - image: docker:19
    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          key: oneko-catnip-artifacts-{{ or .Environment.CIRCLE_TAG .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          key: catnip-frontend-{{ or .Environment.CIRCLE_TAG .Environment.CIRCLE_SHA1 }}
      - run: mv /home/circleci/project/frontend/dist ./frontend/dist
      - run: cp ./circle-artifacts/o-neko-catnip .
      - run: docker build -t subshellgmbh/o-neko-catnip:latest .
      - run: docker tag subshellgmbh/o-neko-catnip:latest subshellgmbh/o-neko-catnip:$CIRCLE_TAG
      - run: echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
      - run: docker push subshellgmbh/o-neko-catnip:latest
      - run: docker push subshellgmbh/o-neko-catnip:$CIRCLE_TAG

workflows:
  version: 2
  build_and_test:
    jobs:
      - frontend:
          filters:
            tags:
              only: /.*/
      - backend:
          context:
            - docker.subshell.com
          filters:
            tags:
              only: /.*/
      - dockerize_dev:
          requires:
            - frontend
            - backend
          context:
            - dockerhub
          filters:
            branches:
              only: master
            tags:
              only: /.*/
      - release:
          requires:
            - frontend
            - backend
          context:
            - dockerhub
          filters:
            branches:
              ignore: /.*/
            # only act on version tag
            tags:
              only: /^[0-9]+(\.[0-9]+)*$/
