version: 2.1
jobs:
  build:
    docker:
      - image: docker.subshell.com/builder/golang-builder:0.3.0
        auth:
          username: $DOCKER_USERNAME
          password: $DOCKER_PASSWORD
    steps:
      - checkout
      - restore_cache:
          keys:
            - oneko-url-trigger-go-mod-{{ checksum "go.sum" }}
      - run:
          name: Install dependencies
          command: go mod download
      - save_cache:
          key: oneko-url-trigger-go-mod-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"
      - run:
          name: Build the application
          command: make go-build-for-docker
      - run: mkdir ./circle-artifacts && cp ./o-neko-url-trigger ./circle-artifacts/
      - save_cache:
          key: oneko-url-trigger-artifacts-{{ .Environment.CIRCLE_SHA1 }}
          paths: 
            - ./circle-artifacts/
      - store_artifacts:
          path: ./circle-artifacts/

  dockerize_dev:
    docker:
      - image: docker:19
    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          key: oneko-url-trigger-artifacts-{{ .Environment.CIRCLE_SHA1 }}
      - run: cp ./circle-artifacts/o-neko-url-trigger .
      - run: docker build -t subshellgmbh/o-neko-url-trigger:latest-dev .
      - run: echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
      - run: docker push subshellgmbh/o-neko-url-trigger:latest-dev

  release:
    docker:
      - image: docker:19
    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          key: oneko-url-trigger-artifacts-{{ .Environment.CIRCLE_SHA1 }}
      - run: cp ./circle-artifacts/o-neko-url-trigger .
      - run: docker build -t subshellgmbh/o-neko-url-trigger:latest .
      - run: docker tag subshellgmbh/o-neko-url-trigger:latest subshellgmbh/o-neko-url-trigger:$CIRCLE_TAG
      - run: echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
      - run: docker push subshellgmbh/o-neko-url-trigger:latest
      - run: docker push subshellgmbh/o-neko-url-trigger:$CIRCLE_TAG

workflows:
  version: 2
  build:
    jobs:
      - build:
          context:
            - docker.subshell.com
          filters:
            tags:
              only: /.*/
      - dockerize_dev:
          requires:
            - build
          context:
            - dockerhub
          filters:
            #branches:
            #  only: master
            tags:
              only: /.*/
      - release:
          requires:
            - build
          context:
            - dockerhub
          filters:
            branches:
              ignore: /.*/
            # only act on version tag
            tags:
              only: /^[0-9]+(\.[0-9]+)*$/
